// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vantage.Api.Persistence;

#nullable disable

namespace Vantage.Api.Persistence.Migrations
{
    [DbContext(typeof(VantageDbContext))]
    [Migration("20260921214038_EarthquakeObservations")]
    partial class EarthquakeObservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vantage.Api.Persistence.WorkspaceRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("workspaces", "platform");
                });

            modelBuilder.Entity("Vantage.Api.Platform.Observations.CurrentAircraftRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OrderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Position")
                        .HasColumnType("geography (point,4326)");

                    b.Property<string>("RecordJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Position");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Position"), "gist");

                    b.HasIndex("RetrievedAt");

                    b.HasIndex("SourceId", "RetrievedAt");

                    b.ToTable("current_aircraft", "atlas");
                });

            modelBuilder.Entity("Vantage.Api.Platform.Observations.CurrentEarthquakeRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("InLatestFeed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("OrderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Position")
                        .HasColumnType("geography (point,4326)");

                    b.Property<string>("RecordJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Position");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Position"), "gist");

                    b.HasIndex("SourceId", "InLatestFeed", "OccurredAt");

                    b.ToTable("current_earthquakes", "atlas");
                });

            modelBuilder.Entity("Vantage.Api.Platform.Observations.EarthquakeFeedRow", b =>
                {
                    b.Property<string>("SourceId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rejected")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.Property<bool>("Truncated")
                        .HasColumnType("boolean");

                    b.HasKey("SourceId");

                    b.ToTable("earthquake_feeds", "atlas");
                });

            modelBuilder.Entity("Vantage.Api.Platform.Observations.ObservationRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Position")
                        .HasColumnType("geography (point,4326)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RecordJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Position");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Position"), "gist");

                    b.HasIndex("RetrievedAt");

                    b.HasIndex("EntityId", "ObservedAt");

                    b.HasIndex("DataType", "SourceId", "RetrievedAt");

                    b.ToTable("observations", "platform");
                });
#pragma warning restore 612, 618
        }
    }
}
