// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vantage.Api.Persistence;

#nullable disable

namespace Vantage.Api.Persistence.Migrations
{
    [DbContext(typeof(VantageDbContext))]
    partial class VantageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vantage.Api.Persistence.PersonalPreferencesRow", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("DefaultRegion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("personal_preferences", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_personal_preferences_region", "\"DefaultRegion\" IN ('northern-europe', 'denmark', 'europe', 'world')");

                            t.HasCheckConstraint("CK_personal_preferences_theme", "\"Theme\" IN ('dark', 'light')");
                        });
                });

            modelBuilder.Entity("Vantage.Api.Persistence.WorkspaceRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "UpdatedAt");

                    b.ToTable("workspaces", "platform");
                });

            modelBuilder.Entity("Vantage.Api.Platform.Connections.ConnectionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ConnectorTypeId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialRef")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TemplateId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("TemplateVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "RemovedAt");

                    b.ToTable("connections", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_connections_scope", "(\"Scope\" = 'global' AND \"WorkspaceId\" IS NULL) OR (\"Scope\" = 'workspace' AND \"WorkspaceId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Vantage.Api.Platform.Connections.ConnectionSecretRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.ToTable("connection_secrets", "private");
                });

            modelBuilder.Entity("Vantage.Api.Platform.Connections.DatasetRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "ProductId")
                        .IsUnique();

                    b.ToTable("datasets", "platform");
                });

            modelBuilder.Entity("Vantage.Api.Platform.Connections.ObservationDeliveryRow", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ObservationId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<long>("ConfigurationRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("DatasetId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConnectionId", "ObservationId", "ConfigurationRevision");

                    b.HasIndex("ObservationId");

                    b.HasIndex("DatasetId", "RetrievedAt");

                    b.ToTable("observation_deliveries", "platform");
                });

            modelBuilder.Entity("Vantage.Api.Platform.Identity.PlatformUserRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<long>("AccessRevision")
                        .HasColumnType("bigint");

                    b.Property<bool>("CanUseData")
                        .HasColumnType("boolean");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("users", "platform");
                });

            modelBuilder.Entity("Vantage.Api.Platform.Observations.CurrentAircraftRow", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OrderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Position")
                        .HasColumnType("geography (point,4326)");

                    b.Property<string>("RecordJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConnectionId", "Id");

                    b.HasIndex("Position");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Position"), "gist");

                    b.HasIndex("RetrievedAt");

                    b.HasIndex("SourceId", "RetrievedAt");

                    b.ToTable("current_aircraft", "platform");
                });

            modelBuilder.Entity("Vantage.Api.Platform.Observations.CurrentEarthquakeRow", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("InLatestFeed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("OrderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Position")
                        .HasColumnType("geography (point,4326)");

                    b.Property<string>("RecordJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConnectionId", "Id");

                    b.HasIndex("Position");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Position"), "gist");

                    b.HasIndex("SourceId", "InLatestFeed", "OccurredAt");

                    b.ToTable("current_earthquakes", "platform");
                });

            modelBuilder.Entity("Vantage.Api.Platform.Observations.EarthquakeFeedRow", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SourceId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rejected")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.Property<bool>("Truncated")
                        .HasColumnType("boolean");

                    b.HasKey("ConnectionId", "SourceId");

                    b.ToTable("earthquake_feeds", "platform");
                });

            modelBuilder.Entity("Vantage.Api.Platform.Observations.ObservationRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Position")
                        .HasColumnType("geography (point,4326)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RecordJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Position");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Position"), "gist");

                    b.HasIndex("RetrievedAt");

                    b.HasIndex("EntityId", "ObservedAt");

                    b.HasIndex("DataType", "SourceId", "RetrievedAt");

                    b.ToTable("observations", "platform");
                });

            modelBuilder.Entity("Vantage.Api.Persistence.PersonalPreferencesRow", b =>
                {
                    b.HasOne("Vantage.Api.Platform.Identity.PlatformUserRow", null)
                        .WithOne()
                        .HasForeignKey("Vantage.Api.Persistence.PersonalPreferencesRow", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vantage.Api.Persistence.WorkspaceRow", b =>
                {
                    b.HasOne("Vantage.Api.Platform.Identity.PlatformUserRow", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vantage.Api.Platform.Connections.ConnectionRow", b =>
                {
                    b.HasOne("Vantage.Api.Platform.Identity.PlatformUserRow", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vantage.Api.Platform.Connections.ConnectionSecretRow", b =>
                {
                    b.HasOne("Vantage.Api.Platform.Connections.ConnectionRow", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vantage.Api.Platform.Connections.DatasetRow", b =>
                {
                    b.HasOne("Vantage.Api.Platform.Connections.ConnectionRow", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vantage.Api.Platform.Connections.ObservationDeliveryRow", b =>
                {
                    b.HasOne("Vantage.Api.Platform.Connections.ConnectionRow", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantage.Api.Platform.Connections.DatasetRow", null)
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantage.Api.Platform.Observations.ObservationRow", null)
                        .WithMany()
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
